(.devops) ubuntu@ip-172-31-10-130:~/project-ml-microservice-kubernetes$ ./run_kubernetes.sh
Error from server (AlreadyExists): pods "udacity-ml-microservice" already exists
NAME                      READY   STATUS    RESTARTS   AGE
udacity-ml-microservice   1/1     Running   0          42s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000
^C(.devops) ubuntu@ip-172-31-10-130:~/project-ml-microservice-kubernetes$ ^C
(.devops) ubuntu@ip-172-31-10-130:~/project-ml-microservice-kubernetes$ kubectl logs udacity-ml-microservice
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 306-778-063
[2022-08-13 11:36:59,514] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-08-13 11:36:59,528] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-08-13 11:36:59,537] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
127.0.0.1 - - [13/Aug/2022 11:36:59] "POST /predict HTTP/1.1" 200 -
(.devops) ubuntu@ip-172-31-10-130:~/project-ml-microservice-kubernetes$